name: enationn
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Flutter Default...
  cupertino_icons: ^1.0.2

  #Provider...
  provider: ^6.0.5

  #Decorations...
  page_transition: ^2.0.9
  google_fonts: ^4.0.3
  custom_sliding_segmented_control: ^1.7.4

  #Flutter Notification..
  # flutter_local_notifications: ^14.1.0

  #Api Calls...
  http: ^0.13.5

  #Date Time...
  intl: ^0.18.0

  #Shared Pref...
  shared_preferences: ^2.1.0

  #Email Validator...
  email_validator: ^2.1.17
  email_otp: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Dashboard/
    - assets/SplashScreenImg/
    - assets/LoginSignupScreen/
    - assets/Logos/
    - assets/PaymentScreenImg/
    - assets/PopUpScreenImages/
    - assets/ProfileScreen/
    - assets/ExtrasScreens/
