name: enationn
description: A new Flutter project.
publish_to: "none"

version: 1.0.6+8

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Flutter Default...
  cupertino_icons: ^1.0.2

  #Provider...
  provider: ^6.0.5

  #Decorations...
  page_transition: ^2.0.9
  google_fonts: ^4.0.3
  custom_sliding_segmented_control: ^1.7.4
  font_awesome_flutter: ^10.5.0
  smooth_page_indicator: ^1.1.0
  share_plus: ^7.0.2
  fluttertoast: ^8.2.2

  #Api Calls...
  http: ^0.13.5

  #Date Time...
  intl: ^0.18.0

  #Shared Pref...
  shared_preferences: ^2.1.0

  #Email Validator...
  email_validator: ^2.1.17
  email_otp: ^2.0.1

  #Email ...
  change_app_package_name: ^1.1.0
  quiver: ^3.2.1
  mailer: ^6.0.1

  # url Launcher
  url_launcher: ^6.1.11
  email_auth: ^1.0.0
  flutter_email_sender: ^6.0.1
  flutter_animate: ^4.2.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Dashboard/
    - assets/SplashScreenImg/
    - assets/LoginSignupScreen/
    - assets/Logos/
    - assets/PaymentScreenImg/
    - assets/PopUpScreenImages/
    - assets/ProfileScreen/
    - assets/ExtrasScreens/
    - assets/Email/
